-- SELECT first_name, last_name
-- FROM actor;
-- SELECT CONCAT(first_name,' ', last_name) AS  "Actor Name"
-- FROM actor;
-- SELECT actor_id , first_name, last_name
-- FROM actor 
-- WHERE first_name = "Joe";
-- SELECT actor_id, first_name, last_name
-- FROM actor 
-- where last_name LIKE "%GEN%";
-- SELECT actor_id, first_name, last_name
-- FROM actor 
-- where last_name LIKE "%LI%"
-- ORDER BY last_name, first_name;
-- SELECT country_id, country
-- FROM country
-- WHERE country IN ("Afghanistan", "Bangladesh", "China");
-- ALTER TABLE actor
-- ADD COLUMN middle_name VARCHAR(45) AFTER first_name;
-- ALTER TABLE actor
-- MODIFY COLUMN middle_name BLOB;
-- SELECT last_name , COUNT(*) as actor_count
-- FROM actor
-- GROUP BY last_name;
-- SELECT last_name , COUNT(*) as actor_count
-- FROM actor
-- GROUP BY last_name
-- HAVING COUNT(*) >= 2;
-- SELECT S.first_name, S.last_name, A.address
-- FROM staff AS S
-- JOIN address AS A ON A.address_id = S.address_id; 
-- SELECT S.first_name, S.last_name, SUM(P.amount)
-- FROM staff AS S
-- JOIN payment AS P ON P.staff_id = S.staff_id
-- WHERE P.payment_date BETWEEN '2005-08-01' AND '2005-08-31'
-- GROUP BY S.staff_id, S.first_name, S.last_name; 
-- SELECT F.title , COUNT(FA.actor_id) as actor_count 
-- FROM film_actor AS FA 
-- JOIN film AS F ON FA.film_id = F.film_id
-- GROUP BY F.title; 
-- SELECT COUNT(*) as copies
-- FROM film AS F 
-- JOIN inventory AS I ON I.film_id = F.film_id
-- WHERE F.title = "Hunchback Impossible";
-- SELECT title 
-- FROM film
-- WHERE language_id = (
--     SELECT L.language_id
--     FROM language AS L
--     WHERE L.name = "English"
-- ) 
-- AND (title LIKE "K%" OR title LIKE "%Q");
-- SELECT first_name , last_name 
-- FROM actor 
-- WHERE actor_id  IN (
--     SELECT actor_id
--     FROM film_actor
--     WHERE film_id = (
--         SELECT film_id
--         FROM film
--         WHERE title = "Alone Trip"
--     )
-- );
-- SELECT C.first_name, C.last_name , C.email
-- FROM customer AS C 
-- JOIN address As A ON A.address_id = C.address_id
-- JOIN city AS C__ ON C__.city_id = A.city_id
-- JOIN country AS C_ ON C_.country_id = C__.country_id
-- WHERE C_.country = "Canada";
-- SELECT F.title
-- FROM film AS F 
-- JOIN film_category AS FM on FM.film_id = F.film_id
-- JOIN category AS C on C.category_id = FM.category_id
-- WHERE C.name = "Family";
-- CREATE VIEW top_five_genres AS
-- SELECT 
--     C.name AS category,
--     SUM(P.amount) AS total_revenue
-- FROM payment AS P
-- JOIN rental AS R ON P.rental_id = R.rental_id
-- JOIN inventory AS I ON R.inventory_id = I.inventory_id
-- JOIN film AS F ON I.film_id = F.film_id
-- JOIN film_category AS FC ON F.film_id = FC.film_id
-- JOIN category AS C ON FC.category_id = C.category_id
-- GROUP BY C.name
-- ORDER BY total_revenue
-- LIMIT 5;
-- SELECT * 
-- FROM top_five_genres
-- ORDER BY total_revenue DESC;
-- SELECT 
--     s.store_id,
--     ci.city,
--     co.country
-- FROM store AS s
-- JOIN address AS a ON s.address_id = a.address_id
-- JOIN city AS ci ON a.city_id = ci.city_id
-- JOIN country AS co ON ci.country_id = co.country_id ;
SELECT s.store_id,
    SUM(p.amount) AS total_sales
FROM store AS s
    JOIN inventory AS i ON s.store_id = i.store_id
    JOIN rental AS r ON i.inventory_id = r.inventory_id
    JOIN payment AS p ON r.rental_id = p.rental_id
GROUP BY s.store_id;